### ISSUE TITLE
Erro ao inicializar projeto `this.tree.readText is not a function`

### ISSUE THREAD

**Issue by jhonatasfender** [wizsolucoes/web-components-schematic#5]
Fui executar a inicialização padrão conforme a documentação, só que apresentou um erro 

![image](https://github.com/wizsolucoes/web-components-schematic/assets/12156037/f99a24b7-9153-400f-ac3e-04418967afa5)

```this.tree.readText is not a function```

**Comment by raulmelo** [comment]
@jhonatasfender, atualizei o projeto documentando os suporte a cada versão que o script usa. 

Obrigado.
