### ISSUE TITLE
Inconsistência na parte da documentação

### ISSUE THREAD

**Issue by jhonatasfender** [wizsolucoes/web-components-schematic#6]
Realizando alguns teste percebi que o comando que está no print conforme está no inicio estão diferentes

![image](https://github.com/wizsolucoes/web-components-schematic/assets/12156037/e497610f-9af0-4911-b574-4327e2f161ef)

realizei o teste para verificar se estava disponível:

![image](https://github.com/wizsolucoes/web-components-schematic/assets/12156037/46e41ce4-f263-4ebd-ad7e-c9d03505c4a6)

tentei fazer aqui utilizando markdown mas não encontrei alguma forma que utilizasse conforme o print, ou algo próximo que seja auto explicativo.

**Comment by jhonatasfender** [comment]
dá uma avaliada se curtiu um desses dois

```mermaid
flowchart LR
    ngg["ng g"]
    nggDescription["Angular CLI"]

    pkg["@wizco/schematics-webcomponents:init"]
    pkgDescription["Pacote do NPM"]

    name["quotation"]
    description["Parâmetro Nome"]
    
    selector["-p quotation-module"]
    selectorDescription["Parâmetro Selector Web"]

    ngg --> pkg
    nggDescription --> ngg
    pkg --> name
    pkg --> pkgDescription
    name --> selector
    name --> description
    selector --> selectorDescription
```

```mermaid
graph TD;
    A("ng g") -->|Angular CLI| B("@wizco/schematics-webcomponents:init");
    B -->|Pacote do NPM| C("quotation");
    C -->|Parâmetro Nome| D("-p quotation-module");

```

**Comment by raulmelo** [comment]
@jhonatasfender  Obrigado pelas suas considerações, acabei de subir uma nova versão com esses apontamentos que você observou.
